server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

ai:
  openai:
    base-url: https://api.openai.com/v1
    chat-model: gpt-4o
    tts-model: tts-1
    stt-model: whisper-1

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET:}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    user-info-url: https://kapi.kakao.com/v2/user/me
  google:
    user-info-url: https://www.googleapis.com/oauth2/v3/userinfo

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET:}
    credentials:
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}
      session-token: ${AWS_SESSION_TOKEN:}
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false